# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1300, 650)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.but01 = QtWidgets.QPushButton(self.centralwidget)
        self.but01.setGeometry(QtCore.QRect(0, 0, 98, 50))
        self.but01.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but01.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but01.setText("Предтечи \n"
"фантастики")
        self.but01.setObjectName("but01")
        self.but02 = QtWidgets.QPushButton(self.centralwidget)
        self.but02.setGeometry(QtCore.QRect(100, 0, 98, 50))
        self.but02.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but02.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but02.setText("Научная\n"
"фантастика")
        self.but02.setObjectName("but02")
        self.but03 = QtWidgets.QPushButton(self.centralwidget)
        self.but03.setGeometry(QtCore.QRect(200, 0, 98, 50))
        self.but03.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but03.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but03.setText("Философия и\n"
"социальная \n"
"фантастика")
        self.but03.setObjectName("but03")
        self.but04 = QtWidgets.QPushButton(self.centralwidget)
        self.but04.setGeometry(QtCore.QRect(300, 0, 98, 50))
        self.but04.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but04.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but04.setText("Космическая\n"
"опера")
        self.but04.setObjectName("but04")
        self.but05 = QtWidgets.QPushButton(self.centralwidget)
        self.but05.setGeometry(QtCore.QRect(400, 0, 98, 50))
        self.but05.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but05.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but05.setText("Сатира\n"
"и юмор")
        self.but05.setObjectName("but05")
        self.but06 = QtWidgets.QPushButton(self.centralwidget)
        self.but06.setGeometry(QtCore.QRect(500, 0, 98, 50))
        self.but06.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but06.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but06.setText("Советская\n"
"фантастика")
        self.but06.setObjectName("but06")
        self.but07 = QtWidgets.QPushButton(self.centralwidget)
        self.but07.setGeometry(QtCore.QRect(600, 0, 98, 50))
        self.but07.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but07.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but07.setText("Эпическое\n"
"фентези")
        self.but07.setObjectName("but07")
        self.but08 = QtWidgets.QPushButton(self.centralwidget)
        self.but08.setGeometry(QtCore.QRect(700, 0, 98, 50))
        self.but08.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 7pt \"Monospac821 BT\";")
        self.but08.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but08.setText("Приключенческое\n"
"и героическое\n"
"фэнтези")
        self.but08.setObjectName("but08")
        self.but09 = QtWidgets.QPushButton(self.centralwidget)
        self.but09.setGeometry(QtCore.QRect(800, 0, 98, 50))
        self.but09.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 7,5pt \"Monospac821 BT\";")
        self.but09.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but09.setText("Мифологическая\n"
"фантастика")
        self.but09.setObjectName("but09")
        self.but10 = QtWidgets.QPushButton(self.centralwidget)
        self.but10.setGeometry(QtCore.QRect(900, 0, 98, 50))
        self.but10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but10.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but10.setText("Детско-\n"
"юношеская\n"
"фантастика")
        self.but10.setObjectName("but10")
        self.but11 = QtWidgets.QPushButton(self.centralwidget)
        self.but11.setGeometry(QtCore.QRect(1000, 0, 98, 50))
        self.but11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 9pt \"Monospac821 BT\";")
        self.but11.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but11.setText("Историческая\n"
"фантастика\n"
"и фэнтези")
        self.but11.setObjectName("but11")
        self.but12 = QtWidgets.QPushButton(self.centralwidget)
        self.but12.setGeometry(QtCore.QRect(1100, 0, 98, 50))
        self.but12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 7pt \"Monospac821 BT\";")
        self.but12.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but12.setText("«Тёмная»\n"
"фантастика\n"
"(мистика и хоррор)")
        self.but12.setObjectName("but12")
        self.but13 = QtWidgets.QPushButton(self.centralwidget)
        self.but13.setGeometry(QtCore.QRect(1200, 0, 98, 50))
        self.but13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 216, 194, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 10pt \"Monospac821 BT\";")
        self.but13.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.but13.setText("Другие\n"
"направления\n"
"фантастики")
        self.but13.setObjectName("but13")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 50, 1281, 31))
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "200 книг"))
        self.but01.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but02.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but03.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but04.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but05.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but06.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but07.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but08.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but09.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but10.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but11.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but12.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.but13.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("mainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
